// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ddSpelunker.Cmd;

namespace ddSpelunker.Cmd.Migrations
{
    [DbContext(typeof(SpelunkerContext))]
    partial class SpelunkerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("ddSpelunker.Cmd.DiskDrive", b =>
                {
                    b.Property<int>("DiskDriveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("DiskDriveId");

                    b.ToTable("DiskDrives");
                });

            modelBuilder.Entity("ddSpelunker.Cmd.NuggetFile", b =>
                {
                    b.Property<int>("NuggetFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiskDriveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("NuggetFileId");

                    b.HasIndex("DiskDriveId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("ddSpelunker.Cmd.NuggetFile", b =>
                {
                    b.HasOne("ddSpelunker.Cmd.DiskDrive", "DiskDrive")
                        .WithMany("Files")
                        .HasForeignKey("DiskDriveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiskDrive");
                });

            modelBuilder.Entity("ddSpelunker.Cmd.DiskDrive", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
